manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32p4
id=ag1357.cascadeterrace
version.name=0.1.0
version.code=1
name=Anaphorum
app.0.id=ag1357.cascadeterrace
app.0.name=Anaphorum
app.0.binary=cascadeterrace
app.0.stack.depth=16384
