#!/usr/bin/env python3
"""One fixed ~101K parameter embedding/MLP experiment; only TRAIN gradients,
VALIDATION early selection. No TEST/FINAL loading and no English response targets.
Run with OPENBLAS_NUM_THREADS=1 for reproducibility. Numpy + scipy only.
"""
import os
os.environ.setdefault('OPENBLAS_NUM_THREADS','1')
import numpy as np
from scipy.sparse import csr_matrix
import ctypes as C,json,time,hashlib
from abi import *
from evaluate import load
BUCKETS=1536;WIDTH=64;OUT=sum(SIZES)
def data(split,lib):
 rows=[];cols=[];ys=[];texts=[]
 for w in load(split):
  v=view(w)
  for q in w['cases']:
   fs=(C.c_uint16*160)();n=lib.cg_features(C.byref(v),q['text'].encode(),fs,160);idx=len(ys)
   for f in fs[:n]:rows.append(idx);cols.append(f)
   fr=q['frame'];ys.append([fr[x] for x in ['op','relation','epistemic','act','negation','hypothetical']]);texts.append(q['id'])
 x=csr_matrix((np.ones(len(rows),dtype=np.float32),(rows,cols)),shape=(len(ys),BUCKETS));x=x.multiply(1/np.maximum(1,np.asarray(x.sum(1)))).tocsr()
 return x,np.array(ys),texts

def main():
 lib=library();x,y,ids=data('train',lib);vx,vy,_=data('validation',lib);rng=np.random.default_rng(72191)
 emb=rng.normal(0,.1,(BUCKETS,WIDTH)).astype('f');weights=rng.normal(0,.08,(WIDTH,OUT)).astype('f');bias=np.zeros(OUT,'f');params=[emb,weights,bias];m=[np.zeros_like(a) for a in params];v=[np.zeros_like(a) for a in params]
 off=np.r_[0,np.cumsum(SIZES)];step=0;history=[];best=-1;bestparams=None;start=time.time()
 def accuracy(xx,yy):
  z=np.maximum(xx@emb,0)@weights+bias;p=np.stack([z[:,off[h]:off[h+1]].argmax(1) for h in range(6)],1);return float((p==yy).all(1).mean()),(p==yy).mean(0).tolist()
 for epoch in range(60):
  order=rng.permutation(len(y))
  for a in range(0,len(y),128):
   ii=order[a:a+128];xx=x[ii];yy=y[ii];h=xx@emb;act=np.maximum(h,0);z=act@weights+bias;dz=np.zeros_like(z)
   for hd in range(6):
    lo,hi=off[hd:hd+2];p=z[:,lo:hi];p=np.exp(p-p.max(1,keepdims=True));p/=p.sum(1,keepdims=True);p[np.arange(len(ii)),yy[:,hd]]-=1;dz[:,lo:hi]=p/(len(ii)*6)
   dw=act.T@dz;db=dz.sum(0);dh=(dz@weights.T)*(h>0);de=xx.T@dh;step+=1
   for j,(param,g) in enumerate(zip(params,[de,dw,db])):
    m[j]=.9*m[j]+.1*g;v[j]=.999*v[j]+.001*g*g;param-=.012*(m[j]/(1-.9**step))/(np.sqrt(v[j]/(1-.999**step))+1e-8)
  va,heads=accuracy(vx,vy);history.append({'epoch':epoch+1,'validation_joint':va,'validation_heads':heads})
  if va>best:best=va;bestparams=[p.copy() for p in params];bestepoch=epoch+1
  if epoch%10==9:print(json.dumps(history[-1]),flush=True)
 emb,weights,bias=bestparams
 es=float(np.max(np.abs(emb))/127);ws=float(np.max(np.abs(weights))/127)
 qe=np.clip(np.rint(emb/es),-127,127).astype('int8');qw=np.clip(np.rint(weights/ws),-127,127).astype('int8').T.copy();qb=np.rint(bias/(es*ws)).astype('<i4')
 models=ROOT/'research/models';models.mkdir(exist_ok=True)
 np.savez(models/'decision_training.npz',embedding=emb,weights=weights,bias=bias)
 (models/'decision_int8.bin').write_bytes(qe.tobytes()+qw.tobytes()+qb.tobytes())
 def array(name,a,typ):return f'static const {typ} {name}'+''.join(f'[{n}]' for n in a.shape)+'={'+','.join('{'+','.join(map(str,row))+'}' for row in a) +'};\n' if a.ndim==2 else f'static const {typ} {name}[{len(a)}]={{'+','.join(map(str,a))+'};\n'
 (models/'decision_int8.inc').write_text('/* Generated by research/train.py. TRAIN gradients; VALIDATION selection only. */\n'+array('cg_embedding',qe,'int8_t')+array('cg_weights',qw,'int8_t')+array('cg_bias',qb,'int32_t'))
 report={'architecture':'1536 hashed word/bigram buckets x 64 shared embedding; pooled ReLU; 6 independent linear heads','parameters':int(emb.size+weights.size+bias.size),'quantized_bytes':int(qe.nbytes+qw.nbytes+qb.nbytes),'float_training_bytes':int(emb.nbytes+weights.nbytes+bias.nbytes),'head_sizes':SIZES,'heads':['operator','relation','epistemic','speech_act','negation','intervention'],'training_worlds':160,'training_utterances':len(y),'validation_worlds':32,'epochs':60,'selected_epoch':bestepoch,'selection':'validation joint frame-head accuracy','best_validation_joint_heads':best,'seconds':time.time()-start,'history':history,'seed':72191,'int8_embedding_scale':es,'int8_output_scale':ws,'training_ids_sha256':hashlib.sha256('\n'.join(ids).encode()).hexdigest(),'test_or_final_loaded':False,'confidence':'uncalibrated margin; not used to authorize propositions','limitations':['bag of word/bigram order, no learned long-term recurrent state','entity binding supplied by deterministic data-driven linker','second relation has no learned head; evaluated as failure','int8 activations average with truncation, no floating point in C inference']}
 (ROOT/'research/results/training.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:v for k,v in report.items() if k!='history'},indent=2))
if __name__=='__main__':main()
